# Generated by Django 4.1 on 2022-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_description_fish_scientific_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='scientific_name',
        ),
        migrations.AlterField(
            model_name='fish',
            name='category',
            field=models.CharField(max_length=12),
        ),
    ]
