# Generated by Django 4.1 on 2022-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_fish_name_remove_fish_scientific_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='category',
            field=models.CharField(choices=[('F', 'Freshwater'), ('S', 'Saltwater'), ('A', 'Anadromous')], default='F', max_length=1),
        ),
    ]
