# Generated by Django 4.1 on 2022-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_fish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='name',
            field=models.CharField(default='fish', max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
