# Generated by Django 4.1 on 2022-08-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fish_name_fish_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='picture',
            field=models.URLField(default=''),
        ),
    ]
