# Generated by Django 4.1 on 2022-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
