# Generated by Django 4.1 on 2022-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_caught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caught',
            name='date',
            field=models.DateField(verbose_name='Catch Date'),
        ),
    ]
