# Generated by Django 4.1 on 2022-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_lure_alter_caught_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='lures',
            field=models.ManyToManyField(to='main_app.lure'),
        ),
    ]
